### ISSUE TITLE
Bad example for loading data

### ISSUE THREAD

**Issue by Henry-E** [switchboard-xyz/switchboard-v2#48]
https://github.com/switchboard-xyz/switchboard-v2/blob/6a58d6e2f4ba0122c05aa68f3f64e294057373d3/examples/programs/anchor-feed-parser/src/lib.rs#L12-L15

https://github.com/switchboard-xyz/switchboard-v2/blob/6a58d6e2f4ba0122c05aa68f3f64e294057373d3/examples/programs/anchor-feed-parser/src/lib.rs#L32-L39

This account should really be loaded using the build in `AccountLoader` keyword.
`pub aggregator: AccountLoader<'info, AggregatorAccountData >, `
And you can use the `cfg()` functionality to switch the program id depending on whether it's deployed to mainnet or devnet

at the top of the lib.rs file, before the #[program] macro, for instance
```
#[cfg(feature = "mainnet")]
declare_id!("8ghymvPffJbkLHqYfSKdE8moRH5gSf4AQav9qtZfu77H");
#[cfg(not(feature = "mainnet"))]
declare_id!("DLANS7Qh31fFWLujEMtn5kyd87H8ZUbhwtfMurrSHYn9");
```
That way when the user compiles their own program, they just need to pass a feature flag and it will compile with the correct program ID. And you don't have to reimplement all the anchor checks.

Can check here for more details https://solana.stackexchange.com/questions/848/how-to-have-a-different-program-id-depending-on-the-cluster/852#852

**Comment by gallynaut** [comment]
Thanks for pointing that out! We use that feature for our program but for some reason never thought to add it to the rust crate. This saved me alot of headaches so thanks again.

**Comment by Henry-E** [comment]
Glad it was helpful!
