### ISSUE TITLE
Cannot use AggregatorAccountData on Devnet

### ISSUE THREAD

**Issue by ngundotra** [switchboard-xyz/switchboard-v2#56]
Using it with Anchor throws an AnchorAccountError
```
> Program logged: "Instruction: Initialize"
> Program logged: "AnchorError caused by account: aggregator. Error Code: AccountOwnedByWrongProgram. Error Number: 3007. Error Message: The given account is owned by a different program than expected."
> Program logged: "Left:"
> Program logged: "2TfB33aLaneQb5TNVwyDz3jSZXS6jdW2ARw1Dgf84XCG"
> Program logged: "Right:"
> Program logged: "SW1TCH7qEPTdLsDHRgPuMQjbQxKdH2aBStViMFnt64f"
```

Example transaction on [explorer](https://explorer.solana.com/tx/31mH99GDwfrvF1oCqm87WZhfQXnpfrrYM2WD5QSK3xNhJ8Lugg1tThJQ8ZSapHZ27ZDZ1fUPA1hQYmE9CH9xyMei?cluster=devnet).

Code located [here](https://github.com/ngundotra/switchboard-github-pr/blob/master/tests/sbv2-gh-pr-tracker.ts). 

Executed at top level directory `anchor test --provider.cluster devnet --skip-deploy --skip-build --skip-local-validator`

**Comment by gallynaut** [comment]
Hey, so we added a feature flag that defaults the program ID to mainnet in the switchboard-v2 crate. So in order to use devnet you'll need to enable the feature like this

```toml
switchboard-v2 = { version = "^0.1.14", features = ["devnet"] }
```

**Comment by ngundotra** [comment]
Thank you! 🙏
